# 异常含义
程序执行过程中出现的非正常的流程现象,异常捕获能够减轻对程序的伤害，避免崩溃，ANR问题的产生。
# 异常捕获方式
```Python
try:
	# 可能引发异常现象的代码
except:
	# 出现异常现象的处理代码
else:
	# 未出现异常现象的处理代码
finally：
	 # try代码块结束后运行的代码
 ## finally：无论是否有异常都会执行

'''
捕获多个异常错误
'''
try:
    print(a)
except (NameError,KeyError):
    print("执行这句就代表错误")
    
''' 
万能异常：Exception，可以捕获任意异常类型,
as相当于取别名，e是变量名，可以自定义，as e 相当于把异常信息保存在变量e中
'''
try:
    print(a)
except Exception as e :
    print("执行这句就代表错误")
    print(e)
else：
	print("无问题")

```
# 自定义异常
```Python
def funa():
    print("hello")
    raise Exception("此处抛出一个异常")
funa()
```


# 案例一
# 密码长度不够，则报异常，输入密码超过6位方可
```Python
def inp():
    pwd = input("请输入密码")
    if len(pwd) >= 6:
        return "密码输入成功"
    raise Exception("长度不够")
try:
    print(inp())
except Exception as e:
    print(e)
```
# 案例二
```Python
try:
    num = int(input("请输入一个整数"))
    result = 8/num
    print(result)
# except ZeroDivisionError:
#     print("分母不能为0")
except ValueError:
    print("请输入正确的整数")
except Exception as res:
    print("未知错误%s"%res)
else:
    print("程序正常执行")
finally:
    print("无论是否异常，都会执行")
```
# 异常的传递
当函数/方法执行出现异常，会将异常传递给函数/方法的调用一方，如果传递到主函数，仍然没有异常处理，程序才会被终止。因此，可以在主函数中，增加异常捕获
```Python
def demo1():
    return int(input("请输入一个整数"))
def demo2():
    return demo1()
try:
    print(demo2())
except Exception as result:
    print("未知错误%s" %result)

请输入一个整数d
未知错误invalid literal for int() with base 10: 'd'
```
# 抛出raise异常
1.创建Exception异常对象
2.使用raise抛出异常
```Python
def input_password():
    pw = input("请输入密码")
    if len(pw) >= 8:
        return pw
    print("主动抛出异常")
    # 1.创建异常对象-可以使用错误信息字符串作为参数
    ex = Exception("密码长度不够")
    #2.主动抛出异常
    raise ex
#3.捕获异常
try:
    print(input_password())
except Exception as result:
    print(result)
```
